language: php

sudo: required

addons:
  postgresql: "9.6"

cache:
  directories:
  - $HOME/.composer/cache

php:
- 7.1

services:
- mysql

env:
  global:
  - DB=pgsql
  matrix:
  - MOODLE_BRANCH=MOODLE_35_STABLE
  - MOODLE_BRANCH=MOODLE_36_STABLE
  - MOODLE_BRANCH=MOODLE_37_STABLE
  - MOODLE_BRANCH=MOODLE_38_STABLE
  - MOODLE_BRANCH=master

matrix:
  include:
  # This plugin is not database intensive, just a few tests in mysqli should be enough.
  - php: 7.2
    env: DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE
  - php: 7.2
    env: DB=mysqli MOODLE_BRANCH=MOODLE_310_STABLE
  - php: 7.2
    env: DB=pgsql MOODLE_BRANCH=master
  # Moodle 3.4+ requires PHP 7.
  exclude:
  - php: 7.1
    env: MOODLE_BRANCH=master


before_install:
- phpenv config-rm xdebug.ini
- cd ../..
- composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3;
- export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
- moodle-plugin-ci install -vvv

script:
#- php moodle/local/envbar/tests/privacy/privacy.php
- moodle-plugin-ci phplint
- moodle-plugin-ci phpcpd
- moodle-plugin-ci phpmd
- moodle-plugin-ci codechecker
- moodle-plugin-ci validate
- moodle-plugin-ci phpunit -vvv
- moodle-plugin-ci behat
